/*
 * Generated by tcelm from LambdaTest
 * DO NOT EDIT - This file is auto-generated
 */

#include <stdio.h>
#include <string.h>
#include "tcelm_arena.h"
#include "tcelm_types.h"
#include "tcelm_basics.h"

/* Type definitions */

/* Forward declarations */
static tcelm_value_t *elm_addOne(tcelm_arena_t *arena, tcelm_value_t *);
static tcelm_value_t *elm_pipeline(tcelm_arena_t *arena, tcelm_value_t *);
static tcelm_value_t *elm_main(tcelm_arena_t *arena);

/* Function implementations */

static tcelm_value_t *elm_addOne(tcelm_arena_t *arena, tcelm_value_t *arg0) {
    tcelm_value_t *elm_x = arg0;
    return tcelm_apply(arena, ({
            auto tcelm_value_t *__lambda_impl(tcelm_arena_t *__a, tcelm_value_t **args) {
                tcelm_arena_t *arena = __a;
                tcelm_value_t *elm_n = args[0];
                return tcelm_add_int(arena, elm_n, tcelm_int(arena, 1));
            }
            tcelm_closure(arena, __lambda_impl, 1);
        }), elm_x);
}

static tcelm_value_t *elm_pipeline(tcelm_arena_t *arena, tcelm_value_t *arg0) {
    tcelm_value_t *elm_x = arg0;
    return tcelm_apply(arena, ({
            auto tcelm_value_t *__lambda_impl(tcelm_arena_t *__a, tcelm_value_t **args) {
                tcelm_arena_t *arena = __a;
                tcelm_value_t *elm_n = args[0];
                return tcelm_mul_int(arena, elm_n, tcelm_int(arena, 2));
            }
            tcelm_closure(arena, __lambda_impl, 1);
        }), elm_x);
}

static tcelm_value_t *elm_main(tcelm_arena_t *arena) {

    return tcelm_add_int(arena, elm_addOne(arena, tcelm_int(arena, 5)), elm_pipeline(arena, tcelm_int(arena, 3)));
}
