module Reporting.Error.Syntax exposing (..)

{-| Syntax error types for the parser.
This module defines all the error types used during parsing.
We use a single Problem type to simplify error handling.
-}


-- UNIFIED PROBLEM TYPE


type Problem
    = -- Module
      ModuleBadEnd
    | ModuleProblem
    | ModuleName
    | ModuleSpace
    | ModuleExposing
    | PortModuleProblem
    | PortModuleName
    | PortModuleExposing
    | FreshLine
      -- Import
    | ImportStart
    | ImportName
    | ImportAs
    | ImportAlias
    | ImportExposing
    | ImportExposingList
    | ImportEnd
    | ImportIndentName
    | ImportIndentAlias
    | ImportIndentExposingList
    | Effect
      -- Declaration
    | DeclStart
    | Declarations
    | Decl
    | DeclSpace
      -- Comments
    | LineCommentStart
    | MultiCommentStart
    | MultiCommentEnd
      -- Expressions
    | Start
    | Char
    | String
    | Number
    | Space
    | Dot
    | Access
    | OperatorRight String
    | OperatorReserved
    | IndentOperatorRight String
      -- List
    | List
    | ListSpace
    | ListOpen
    | ListEnd
    | ListIndentOpen
    | ListIndentExpr
    | ListIndentEnd
      -- Function
    | Func
    | FuncSpace
    | FuncArg
    | FuncIndentArg
    | FuncIndentArrow
    | FuncIndentBody
    | FuncArrow
    | FuncBody
      -- Case
    | Case
    | CaseSpace
    | CaseOf
    | CasePattern
    | CaseBranch
    | CaseIndentExpr
    | CaseIndentOf
    | CaseIndentPattern
    | CaseIndentArrow
    | CaseIndentBranch
    | CaseArrow
    | CaseExpr
    | CasePatternAlignment
      -- If
    | If
    | IfSpace
    | IfThen
    | IfCondition
    | IfThenBranch
    | IfElse
    | IfElseBranch
    | IfElseBranchStart
    | IfIndentCondition
    | IfIndentThen
    | IfIndentThenBranch
    | IfIndentElse
    | IfIndentElseBranch
      -- Let
    | Let
    | LetSpace
    | LetIn
    | LetDefName
    | LetDef String
    | LetDestruct
    | LetBody
    | LetIndentDef
    | LetIndentIn
    | LetIndentBody
    | LetDefAlignment
      -- Record
    | Record
    | RecordSpace
    | RecordOpen
    | RecordEnd
    | RecordField
    | RecordEquals
    | RecordExpr
    | RecordIndentOpen
    | RecordIndentField
    | RecordIndentEquals
    | RecordIndentExpr
    | RecordIndentEnd
      -- Tuple
    | Tuple
    | TupleSpace
    | TupleEnd
    | TupleExpr
    | TupleOperatorClose
    | TupleOperatorReserved
    | TupleIndentExpr1
    | TupleIndentExprN
    | TupleIndentEnd
      -- Patterns
    | PStart
    | PChar
    | PString
    | PNumber
    | PFloat Int
    | PAlias
    | PRecord
    | PRecordSpace
    | PRecordField
    | PRecordEnd
    | PRecordOpen
    | PRecordIndentOpen
    | PRecordIndentField
    | PRecordIndentEnd
    | PTuple
    | PTupleSpace
    | PTupleEnd
    | PTupleOpen
    | PTupleExpr
    | PTupleIndentExpr1
    | PTupleIndentExprN
    | PTupleIndentEnd
    | PList
    | PListSpace
    | PListEnd
    | PListOpen
    | PListExpr
    | PListIndentOpen
    | PListIndentExpr
    | PListIndentEnd
    | PIndentStart
    | PIndentAlias
    | PSpace
    | PWildcardNotVar String Int
      -- Types
    | TStart
    | TSpace
    | TIndentStart
    | TRecord
    | TRecordSpace
    | TRecordOpen
    | TRecordEnd
    | TRecordField
    | TRecordColon
    | TRecordType
    | TRecordIndentOpen
    | TRecordIndentField
    | TRecordIndentColon
    | TRecordIndentType
    | TRecordIndentEnd
    | TTuple
    | TTupleSpace
    | TTupleEnd
    | TTupleOpen
    | TTupleType
    | TTupleIndentType1
    | TTupleIndentTypeN
    | TTupleIndentEnd
      -- Definition
    | DefSpace
    | DefEquals
    | DefType
    | DefArg
    | DefIndentEquals
    | DefIndentType
    | DefIndentBody
    | DefBody
    | DefAlignment
    | DefNameRepeat
    | DefNameMatch String
      -- Port
    | Port
    | PortSpace
    | PortName
    | PortColon
    | PortType
    | PortIndentName
    | PortIndentColon
    | PortIndentType
      -- Exposing
    | ExposingStart
    | ExposingValue
    | ExposingOperator
    | ExposingOperatorReserved
    | ExposingOperatorRightParen
    | ExposingEnd
    | ExposingSpace
    | ExposingIndentEnd
    | ExposingIndentValue
    | ExposingTypePrivacy
      -- Destructure
    | DestructSpace
    | DestructPattern
    | DestructEquals
    | DestructBody
    | DestructIndentEquals
    | DestructIndentBody
